In [ ]:
import pandas as pd
import numpy as np
from datetime import datetime
print("Libraries loaded")

Libraries loaded

In [ ]:
# Create messy data like real client data
data = {
    'Customer Name': [' JOHN DOE ', 'jane smith', None, ' JOHN DOE ', 'Chidi Okoro', 'AMAKA ', ''],
    'Email': ['JOHN@GMAIL.COM', 'jane@gmail.com ', 'chidi@YAHOO.COM', 'JOHN@GMAIL.COM', None, 'amaka@gmail.com', 'test@GMAIL.com'],
    'Order Date': ['12/05/2023', '2023.05.12', '05-13-2023', '12/05/2023', '2023/05/14', '14-05-2023', ''],
    'Amount': ['1000', '2500.50', None, '1000', ' 3000 ', 'invalid', '1500'],
    'Region': ['lagos', 'Lagos ', 'ABUJA', 'lagos', 'PH', 'abuja', 'Lagos']
}

df = pd.DataFrame(data)
df.to_csv('messy_data.csv', index=False)
print("Messy file created")
df.head(10)

Messy file created

  Customer Name            Email  Order Date   Amount  Region
0     JOHN DOE    JOHN@GMAIL.COM  12/05/2023     1000   lagos
1    jane smith  jane@gmail.com   2023.05.12  2500.50  Lagos
2          None  chidi@YAHOO.COM  05-13-2023     None   ABUJA
3     JOHN DOE    JOHN@GMAIL.COM  12/05/2023     1000   lagos
4   Chidi Okoro             None  2023/05/14    3000       PH
5        AMAKA   amaka@gmail.com  14-05-2023  invalid   abuja
6                 test@GMAIL.com                 1500   Lagos

In [ ]:
def clean_dataset(file_path):
    # Load file
    df = pd.read_csv(file_path)
    print(f"BEFORE: {df.shape[0]} rows")
    print(df.head())

    # 1. Clean Customer Name: strip spaces, title case, remove empty
    df['Customer Name'] = df['Customer Name'].astype(str).str.strip().str.title()
    df = df[~df['Customer Name'].isin(['', 'None', 'Nan'])]

    # 2. Clean Email: lowercase and strip
    df['Email'] = df['Email'].astype(str).str.strip().str.lower()
    df.loc[df['Email'].isin(['none', 'nan', '']), 'Email'] = np.nan

    # 3. Clean Order Date: handle multiple formats
    df['Order Date'] = pd.to_datetime(df['Order Date'], errors='coerce', dayfirst=True)

    # 4. Clean Amount: convert to number, remove invalid
    df['Amount'] = pd.to_numeric(df['Amount'].astype(str).str.strip(), errors='coerce')

    # 5. Clean Region: standardize
    df['Region'] = df['Region'].astype(str).str.strip().str.title()
    df['Region'] = df['Region'].replace({'Ph': 'Port Harcourt', 'Abuja': 'Abuja', 'Lagos': 'Lagos'})

    # 6. Remove duplicates
    df = df.drop_duplicates()

    # 7. Drop rows where critical data is missing
    df = df.dropna(subset=['Customer Name', 'Amount'])

    print(f"\nAFTER: {df.shape[0]} rows")
    print(df.head())

    return df

clean_df = clean_dataset('messy_data.csv')

BEFORE: 7 rows
  Customer Name            Email  Order Date   Amount  Region
0     JOHN DOE    JOHN@GMAIL.COM  12/05/2023     1000   lagos
1    jane smith  jane@gmail.com   2023.05.12  2500.50  Lagos
2           NaN  chidi@YAHOO.COM  05-13-2023      NaN   ABUJA
3     JOHN DOE    JOHN@GMAIL.COM  12/05/2023     1000   lagos
4   Chidi Okoro              NaN  2023/05/14    3000       PH

AFTER: 3 rows
  Customer Name           Email Order Date  Amount         Region
0      John Doe  john@gmail.com 2023-05-12  1000.0          Lagos
1    Jane Smith  jane@gmail.com        NaT  2500.5          Lagos
4   Chidi Okoro             NaN        NaT  3000.0  Port Harcourt

In [ ]:
# Export to Excel and CSV for client
clean_df.to_csv('clean_data.csv', index=False)
clean_df.to_excel('clean_data.xlsx', index=False)

print("Clean files created! Ready for GitHub.")
clean_df

Clean files created! Ready for GitHub.

  Customer Name           Email Order Date  Amount         Region
0      John Doe  john@gmail.com 2023-05-12  1000.0          Lagos
1    Jane Smith  jane@gmail.com        NaT  2500.5          Lagos
4   Chidi Okoro             NaN        NaT  3000.0  Port Harcourt